# -*- coding: utf-8 -*-
"""GOLD7004_Pi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tEnQRM3f9nzSseJWuJzCrOctwZ9e3NFT

## *PI MonteCarlo*
"""

from random import random
from random import uniform
from math import pi

# Number of random points to be generated
N=90000000

count=0
dentro = 0

# Por simplificação considere o raio = 1 e o círculo centrado na origem (0,0)

for i in range(N):
    point=(uniform(-1,1), uniform(-1,1)) #(x,y)
    if (point[0]**2 + point[1]**2) < 1:         # y < sin(x)
        dentro+=1


answer=(float(dentro)/float(N))*4
print("Estimativa do PI: ",  answer)
print("PI Verdadeiro: ",  pi)
print("Diferença: ",  abs(answer-pi))

